name: Parse resume
on: push

jobs:
  lint:
    name: Spellcheck resume
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: rojopolis/spellcheck-github-actions@0.28.0
        name: Spellcheck
        with: 
          source_files: docs/resume.md
          task_name: Markdown
  build:
    name: Build PDF
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@master
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: docs
          output_dir: pdfs
          build_html: false
      - uses: actions/upload-artifact@v1
        with:
          name: pdfs
          path: pdfs
  deploy:
    name: Release resume
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
      - name: Set date tag
        run: echo "NOW=v$(date +'%Y%m%d.%H%M%S')" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            pdfs/resume.pdf
          tag_name: ${{ env.NOW }}
